### ISSUE TITLE
Stream filter example?

### ISSUE THREAD

**Issue by dkomer** [vlc-qt/examples#1]
Is it possible to show via the examples how to implement a custom stream filter? (for sake of example, something simple like maybe the decomb filter @ https://github.com/videolan/vlc/blob/master/modules/stream_filter/decomp.c)

Just wondering how to do this, like if it needs changes at the vlc-qt level or it's already available to the application that uses that library

Thanks!

**Comment by ntadej** [comment]
This seems to be more directly related to VLC than Qt bindings. Maybe you should ask on their forum.

**Comment by dkomer** [comment]
ah ok, I thought vlc-qt might wrap that part of it too... will play around and see where I get. Thanks :)
