### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by dakom** [vlc-qt/examples#2]
I get this error when trying to run the example:

QWidget: Must construct a QApplication before a QWidget

**Comment by dkomer** [comment]
NM, was due to building in debug mode instead of release mode :)

**Comment by dkomer** [comment]
This error persists when building application in debug mode and using .dll's from nightly build debug folder

**Comment by ntadej** [comment]
Which platform/compiler?

**Comment by dkomer** [comment]
Qt Creator 3.3.1 / MSVC 2013 x64 Kit

**Comment by ntadej** [comment]
Should be fixed with latest version.
