### ISSUE TITLE
Cannot compile vlc-qt example - syntax error

### ISSUE THREAD

**Issue by joehellesen** [vlc-qt/examples#4]
I cannot compile the vlc-qt code.  I am trying to compile EquilizerDialog.cpp using Visual Studio 2010 and the Qt 5.6 plugin.  The compiler chokes on the line:

```
for (QSlider *slider : findChildren<QSlider*>()) {
```

I have never seen a C++ for loop with a colon and no semicolons.  It looks like incorrect syntax.

My compiler says:

1>EqualizerDialog.cpp(31): error C2143: syntax error : missing ',' before ':'
1>EqualizerDialog.cpp(31): error C2143: syntax error : missing ';' before '{'

I have no idea how to use cmake or what the project directory structure should be.  I started a Visual Studio Qt project and added the example files and the windows stuff. Everything compiles except for that.  I am a long time Visual Studio C++ programmer, but new to Qt and cmake.

Any assistance would be greatly appreciated.  I can supply more details if needed.

**Comment by ntadej** [comment]
This is `c++11` standard. Qt 5.7 and later will require it by default. I think Visual Studio 2012 may be required.

Or, you can always rewrite the loop in older syntax.

**Comment by joehellesen** [comment]
Tadej,

Thank you for pointing this out.  It looks like I need to learn more about C++11.  In the mean time I am stuck with the Visual Studio 2010 compiler.  Could you tell me what that line would look like using the older syntax like for(x=0; x <MAX; x++)

The statement below is more complex than my simple example above.

```
for (QSlider *slider : findChildren<QSlider*>()) {
```

Your response will help me understand how the newer range based loops work.

Thank You,

Joe Hellesen

**Comment by ntadej** [comment]
So, the first argument is a name for variable to use in the loop and the second is a list. So it can be rewritten as

``` c++
QList<QSlider*> list = findChildren<QSlider*>();
for (int i = 0; i <  list.size(); i++) {
  list[i]
}
```
