### ISSUE TITLE
Adjusting aspect ratio and stretching screen in simple-player example

### ISSUE THREAD

**Issue by joehellesen** [vlc-qt/examples#5]
I got the simple-player to work. Thanks for your help.  The video does not fill up the window.  I have tried to set the aspect ratio, but it doesn't seem to have any effect.  I am wondering how to control the size of the video display so it will extend to the left and right edges of the screen, much like the vlc.exe player does.  Also wondering how to turn of sub-titles

Thanks

joehellesen

**Comment by ntadej** [comment]
I don't think stretching is supported when rendering on a widget. This is generally not preferred when watching video. I can't even find the option in VLC (on OS X).

As for subtitles, you can use [VlcControlVideo](https://vlc-qt.tano.si/reference/git/classVlcControlVideo.html) class which will give you actions to put in a menu and select subtitles.
