### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget #197

### ISSUE THREAD

**Issue by ShettyRa** [vlc-qt/examples#9]
Hi,

I've installed the vlc-qt librarys and build the simple-player example, by using _MSVC2013_64bit-Debug.
When I try running it, I get the following error(application output):

> Starting C:\Users\rshe\Downloads\examples-master\examples-master\build-simple-player-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\src\debug\simple-player.exe...
> **QWidget: Must construct a QApplication before a QWidget**
> C:\Users\rshe\Downloads\examples-master\examples-master\build-simple-player-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\src\debug\simple-player.exe exited with code 1
Compile Output:

13:04:58: Running steps for project simple-player...
13:04:58: Configuration unchanged, skipping qmake step.
13:04:59: Starting: "C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe" 
	cd src\ && ( if not exist Makefile C:\Qt\Qt5.6.2\5.6\msvc2013_64\bin\qmake.exe C:\Qt\libvlc-qt\src\examples\simple-player\src\src.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
13:04:59: The process "C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe" exited normally.
13:04:59: Elapsed time: 00:01.

I am running the app on Qt creator 5.6.2
I have also added path of all the vlc lib, msvc2013_64/bin to environment variables
I have also provided proper link to the libs
src.pro:

TARGET      = simple-player
TEMPLATE    = app
CONFIG 	   += c++11

QT         += widgets

SOURCES    += main.cpp \
    SimplePlayer.cpp \
    EqualizerDialog.cpp

HEADERS    += SimplePlayer.h \
    EqualizerDialog.h

FORMS      += SimplePlayer.ui \
    EqualizerDialog.ui

INCLUDEPATH += C:\\Qt\\libvlc-qt\\include

LIBS     += -LC:\\Qt\\libvlc-qt\\lib \
        -lVLCQtCore.lib \
        -lVLCQtWidgets.lib
Any hint on what I'm doing wrong?

**Comment by maxriffs** [comment]
Hi, have the same issue :(
